kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "thorntail-demo"
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "thorntail-demo", "kind": "DeploymentConfig"}]'
spec:
  source:
    type: "Git"
    git:
      uri: "http://github.com/hodrigohamalho/thorntail-demo.git"
  strategy:
    type: "JenkinsPipeline"
    jenkinsPipelineStrategy:
      jenkinsfilePath: "infra/pipeline.groovy"